############################################################
#  VLAN CONFIGURATION
############################################################
- name: CONFIGURE VLANs and VLAN to VNI Mapping
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        mapped_vni: "{{ item.vlan_id +10000 }}"
        provider: "{{ nxos_provider }}"
      with_items:
      - "{{ named_leaf_vlans }}"

############################################################
#  Configure SVIs
############################################################

- name: CONFIGURE SVIs THAT ARE MAPPED TO VNIs
      nxos_interface:
        interface: "vlan{{ item.vlan_id }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        admin_state: up
      with_items:
      - "{{ named_leaf_vlans }}"

############################################################
#  Associate Interfaces to vRF
############################################################

- name: ASSOCIATE INTERFACES TO TENANT VRF
      nxos_vrf_interface:
        vrf: "{{ item.vrf }}"
        interface: "vlan{{ item.vlan_id }}"
      with_items:
      - "{{ named_leaf_vlans }}"

############################################################
#  Configure VXLAN VTEP NVE Mapping 
############################################################

- name: CONFIGURE VXLAN VTEP NVE INTERFACE L2VNI MAPPING
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ item.vlan_id +10000 }}"
        multicast_group: "{{ item.mcast_grp }}"
        suppress_arp: true
        provider: "{{ nxos_provider }}"
      with_items:
      - "{{ named_leaf_vlans }}"
